---
title: Code.mil
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  repos:
    title: Repos
    output: true
  uploads:
    title: Uploads
    output: true
email: code@dds.mil
description: DDS is spearheading an effort which will make it easier for DoD to join
  the free and open source communities.
baseurl: "/code.mil.page"
url: 
github_username: deptofdefense
markdown: kramdown
theme: uswds-jekyll
gems:
- jekyll-feed
- uswds-jekyl
sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed