---
title: Code.mil
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  repos:
    title: Repos
    output: true
  uploads:
    title: Uploads
    output: true
email: code@dds.mil
description: DDS is spearheading an effort which will make it easier for DoD to join
  the free and open source communities.
baseurl: "/code.mil.page"
url: 
github_username: deptofdefense
markdown: kramdown
gems:
- jekyll-feed
sass:
  sass_dir: bower_components
  style: compressed
excludes:
- Gemfile
- Gemfile.lock
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Ethan"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      colors: ["red", "green", "blue"]
      layout: "project"
  -
    scope:
      path: ""
      type: "locations"
    values:
      map:
        latitude: 
        longitude: 
