---
title: Code.mil
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  repos:
    title: Repos
    output: true
  uploads:
    title: Uploads
    output: true
email: code@dds.mil
description: DDS is spearheading an effort which will make it easier for DoD to join
  the free and open source communities.
baseurl: "/code.mil.page"
url: 
github_username: deptofdefense
markdown: kramdown
theme: uswds-jekyll
gems:
- jekyll-feed
- uswds-jekyl
sass:
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets
  style: compressed
